#!/usr/bin/env bash
# Usage: awsvm use CONFIG
# Summary: Switch to the specified configuration
# Help: This command will set your environment to use the specified aws configuration

set -e

__awsvm_config $1

# Provide awsvm completions
if [ "$1" = "--complete" ]; then
  exec ls $_AWSVM_ROOT/$configurations
fi

if [[ "$1" == "default" ]] && [ ! -d "$_AWSVM_ROOT/$config_path" ]; then
  printf "${AWSVM_COLOR_RED}No default config set${AWSVM_COLOR_RESET}\\n" >&2
  exit 1
elif [ ! -d "$_AWSVM_ROOT/$config_path" ]; then
  printf "${AWSVM_COLOR_RED}No configuration with that name was found${AWSVM_COLOR_RESET}\\n" >&2
  exit 2
fi

rm -f $current_path
ln -s $config_path $current_path

printf "${AWSVM_COLOR_GREEN}Using aws config \"%s\"${AWSVM_COLOR_RESET}\\n" "$config"
