#!/usr/bin/env bash
# Usage: awsvm list
# Summary: List all the available awsvm configurations
# Help: This command will show you all your available knife aws configurations

set -e

__awsvm_config

default_config=$(readlink $default_path) || true
for c in $(ls $_AWSVM_ROOT/$configurations)
do
  if [[ "$c" == "default" ]]; then
    continue
  fi

  if [[ "$c" == "$config" && "$c" == "$default_config" ]]; then
    printf "${AWSVM_COLOR_GREEN}*=${AWSVM_COLOR_YELLOW} %s${AWSVM_COLOR_RESET}\\n" "$c"
  elif [[ "$c" == "$config" ]]; then
    printf "${AWSVM_COLOR_GREEN}=> %s${AWSVM_COLOR_RESET}\\n" "$c"
  elif [[ "$c" == "$default_config" ]]; then
    printf "${AWSVM_COLOR_YELLOW}*  %s${AWSVM_COLOR_RESET}\\n" "$c"
  else
    printf "   %s\\n" "$c"
  fi
done

echo
printf "${AWSVM_COLOR_GREEN}=>${AWSVM_COLOR_RESET} - current\\n"
printf "${AWSVM_COLOR_GREEN}*=${AWSVM_COLOR_YELLOW}${AWSVM_COLOR_RESET} - current and default\\n"
printf "${AWSVM_COLOR_YELLOW}*${AWSVM_COLOR_RESET}  - default\\n"
