#!/usr/bin/env bash
# Usage: awsvm setup
# Summary: Setup symlinks and put you in a config
# Help: This command is for initial environment load

set -e

__awsvm_config
[[ ! -e "$HOME/.aws" && ! -L "$HOME/.aws" ]] && ln -s $current_path $HOME/.aws

if [[ ! -e "$current_path" ]]; then
  echo "[awsvm] Creating an example aws config and setting it to default"
  awsvm create example > /dev/null
  awsvm default example > /dev/null
fi

config=$(readlink $current_path | sed "s/$configurations\///")
[[ -z "$config" ]] && awsvm use default > /dev/null
