#!/usr/bin/env bash
# Usage: awsvm create CONFIG
# Summary: Create a config in awsvm
# Help: This command will create a aws configuration in awsvm, and switch to using it.

set -e

if [ -z "$1" ]; then
  printf "${AWSVM_COLOR_RED}No name provided${AWSVM_COLOR_RESET}\\n" >&2
  exit 1
fi

__awsvm_config $1

mkdir -p $_AWSVM_ROOT/$config_path

printf "${AWSVM_COLOR_GREEN}Creating configuration: %s${AWSVM_COLOR_RESET}\\n" "$config"
awsvm use $config
printf "${AWSVM_COLOR_YELLOW}Copy your file credentials to ~/.aws and run 'aws help'${AWSVM_COLOR_RESET}\\n"
