#!/usr/bin/env bash
# Usage: awsvm copy CONFIG NEW_CONFIG
# Summary: This will copy one aws configuration to a new name
# Help: This command allows you to clone one configuration to a new name

set -e

__awsvm_config $1

if [ -z "$config" ]; then
  printf "${AWSVM_COLOR_RED}No name provided${AWSVM_COLOR_RESET}\\n" >&2
  exit 1
fi

if [ ! -d $_AWSVM_ROOT/$config_path ]; then
  printf "${AWSVM_COLOR_RED}No configuration named %s found.${AWSVM_COLOR_RESET}\\n" "$1" >&2
  awsvm list
  exit 1
fi

if [ -z "$2" ]; then
  printf "${AWSVM_COLOR_RED}No destination name provided${AWSVM_COLOR_RESET}\\n" >&2
  exit 1
fi

printf "${AWSVM_COLOR_GREEN}Copying: %s to %s${AWSVM_COLOR_RESET}\\n" "$config" "$2"
cp -R $_AWSVM_ROOT/$config_path $_AWSVM_ROOT/$configurations/$2
